{{- if .Values.frontend }}
{{- if .Values.frontend.autoscaling }}
{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cogni-frontend-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cogni-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas | default 4 }}
  metrics:
  {{- if .Values.frontend.autoscaling.targetCPU }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetCPU }}
  {{- end }}
  {{- if .Values.frontend.autoscaling.targetMemory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetMemory }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
