verbosityLevel: 3

# Managed Identity Authentication Config
armAuth:
  type: workloadIdentity
  identityClientID: "74d38441-4134-4589-8ecc-59d5cf649663"
  identityResourceID: "/subscriptions/e3b28d61-42ec-43a8-85ac-9defcc8dbf81/resourceGroups/test-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ingressappgw-cogni-aks"

# Target Azure Application Gateway Config
appgw:
  subscriptionId: "e3b28d61-42ec-43a8-85ac-9defcc8dbf81"
  resourceGroup: "test-rg"
  name: "cogni-appgw"
  usePrivateIP: false

# Kubernetes Config
kubernetes:
  watchNamespace: "" # Watch all namespaces (cogni-dev & cogni-prod)
