repoURL: "https://github.com/cognidispatch/cognidispatch-helm.git"
destinationServer: "https://kubernetes.default.svc"

dev:
  enabled: true
  targetRevision: "production"
  namespace: "cogni-dev"

prod:
  enabled: true
  targetRevision: "production"
  namespace: "cogni-prod"
