apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-ip-masq-agent-config
  namespace: kube-system
  labels:
    component: ip-masq-agent
data:
  ip-masq-agent: |
    nonMasqueradeCIDRs:
      - 10.224.0.0/16
      - 10.220.0.0/16
    masqLinkLocal: false
